apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: wordpress-vpa
  namespace: wordpress
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       "Deployment"
    name:       "wordpress"
  updatePolicy:
    updateMode: "Auto"
